require('texvide.config')
require('texvide.colorscheme')
require('texvide.keymaps')
require('texvide.plugins')
require('texvide.features')

require('texvide.plugin-settings.ultisnips')
require('texvide.plugin-settings.vimtex')
require('texvide.plugin-settings.inkscape_figures')
require('texvide.plugin-settings.nerdtree')
require('texvide.plugin-settings.startify')
require('texvide.plugin-settings.sakls')
-- require('texvide.plugin-settings.autopairs')

require('texvide.advanced-snippets.matrix_shortcuts')