require('texvide.config')
require('texvide.colorscheme')
require('texvide.keymaps')
require('texvide.plugins')
require('texvide.features')
require('texvide.advanced_snippets')

require('texvide.plugin-settings.ultisnips')
require('texvide.plugin-settings.vimtex')
require('texvide.plugin-settings.inkscape_figures')
require('texvide.plugin-settings.nerdtree')
require('texvide.plugin-settings.startify')
require('texvide.plugin-settings.sakls')
