require('texvide.config')
require('texvide.colorscheme')
require('texvide.keymaps')
require('texvide.plugins')
require('texvide.ultisnips')
require('texvide.vimtex')
require('texvide.inkscape_figures')